[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ndmanager"
readme = "README.md"
version = "0.1.1"
authors = [{ name="Nicolas Linden", email="linden.nicolas@orange.fr"}]
description = "Fetching nuclear data"
classifiers = ["Programming Language :: Python :: 3.7"]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/nplinden/ndmanager"

[project.scripts]
ndf = "ndmanager.fetcher.main:main"
ndo = "ndmanager.omcer.main:main"
ndm = "ndmanager.manager.main:main"

[tool.setuptools]
packages = ['ndmanager', 'ndmanager.fetcher', 'ndmanager.omcer']
