[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ndfetcher"
readme = "README.md"
version = "0.1.1"
authors = [{ name="Nicolas Linden", email="linden.nicolas@orange.fr"}]
description = "Fetching nuclear data"
classifiers = ["Programming Language :: Python :: 3.7"]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/nplinden/ndfetcher"

[project.scripts]
ndfetch = "ndfetcher.download:download_cli"
ndprocess = "ndfetcher.generate:generate_cli"
ndchain = "ndfetcher.chain:generate_chain"

[tool.setuptools]
packages = ['ndfetcher']
